apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: forge-django-template
  title: Django App (Forge)
  description: Create a new Django (Python) application using Theodo's Forge
  tags:
    - experimental
    - forge
    - django
    - backend
spec:
  owner: user:wrousseau
  templater: forge
  type: service
  path: '.'
  
  schema:
    required: 
      - component_id
      - description
      - back_end_technology
      - front_end_technology
      - mobile_technology
      - provide_devops_scripts
    properties:
      component_id:
        title: Name
        type: string
        pattern: ^[a-z0-9]+(-[a-z0-9]+)*$
        description: Unique name of the service or website to create. Lowercase, URL-safe characters only.
      description:
        title: Description
        type: string
        description: Help others understand what this service or website is for
      back_end_technology:
        title: Back-end Technology
        type: string
        enum: ["Django (Python)", "Nest.js (Node)", "Serverless", "API Platform / Symfony (PHP)", "None"]
        description: The chosen back-end technology
        default: "Django (Python)"
      front_end_technology:
        title: Front-end Technology
        type: string
        enum: ["None", "React.js", "Next.js (React.js + Server Side Rendering)"]
        description: The chosen front-end technology
        default: "None"
      mobile_technology:
        title: Mobile Technology
        type: string
        enum: ["None", "React Native"]
        description: The chosen mobile technology
        default: "React Native"
      provide_devops_scripts:
        title: Provide Terraform script to provision and deploy to EB environments
        type: boolean
        description: Provide Terraform script to provision and deploy to EB environments
        default: false
