apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: forge-api-platform-template
  title: API Platform App (Forge)
  description: Create a new API Platform / Symfony (PHP) application using Theodo's Forge
  tags:
    - experimental
    - forge
    - php
    - api-platform
    - symfony
    - back-end
spec:
  owner: user:wrousseau
  templater: forge
  type: service
  path: '.'
  
  schema:
    required: 
      - component_id
      - description
      - back_end_technology
      - front_end_technology
    properties:
      component_id:
        title: Name
        type: string
        pattern: ^[a-z0-9]+(-[a-z0-9]+)*$
        description: Unique name of the service or website to create. Lowercase, URL-safe characters only.
      description:
        title: Description
        type: string
        description: Help others understand what this service or website is for
      back_end_technology:
        title: Back-end Technology
        type: string
        enum: ["API Platform / Symfony (PHP)", "Django (Python)", "Nest.js (Node)", "Serverless", "None"]
        description: The chosen back-end technology
        default: "API Platform / Symfony (PHP)"
      front_end_technology:
        title: Front-end Technology
        type: string
        enum: ["None", "React.js", "Next.js (React.js + Server Side Rendering)"]
        description: The chosen front-end technology
        default: "None"
